/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdSettings {
  'betweenCardsAdEnabled' : boolean,
  'headerAdEnabled' : boolean,
  'sidebarAdEnabled' : boolean,
}
export interface Announcement {
  'id' : AnnouncementId,
  'active' : boolean,
  'createdAt' : Timestamp,
  'text' : string,
}
export type AnnouncementId = bigint;
export interface GpaCalculation {
  'id' : bigint,
  'subjects' : Array<GpaSubject>,
  'userId' : StudentId,
  'timestamp' : Timestamp,
  'calculatedGpa' : number,
  'totalCredits' : bigint,
}
export interface GpaSubject {
  'marks' : bigint,
  'credits' : bigint,
  'subjectName' : string,
  'gradePoints' : number,
  'letterGrade' : string,
}
export interface GpaSubjectInput {
  'marks' : bigint,
  'credits' : bigint,
  'subjectName' : string,
}
export type GuestId = string;
export type HashedPassword = string;
export type StudentId = string;
export interface StudentRecord {
  'id' : StudentId,
  'createdAt' : Timestamp,
  'email' : string,
  'hashedPassword' : HashedPassword,
}
export type Timestamp = bigint;
export interface Tool {
  'id' : ToolId,
  'name' : string,
  'usageCount' : bigint,
  'description' : string,
  'enabled' : boolean,
}
export type ToolId = string;
export interface ToolStats { 'usageCount' : bigint, 'toolId' : ToolId }
export interface ToolSummary {
  'perTool' : Array<ToolStats>,
  'toolId' : ToolId,
  'totalUsage' : bigint,
}
export interface VisitorStats { 'totalVisitors' : bigint }
export interface _SERVICE {
  'adminChangePassword' : ActorMethod<[string, string], boolean>,
  'adminCreateAnnouncement' : ActorMethod<[string], Announcement>,
  'adminDeleteAnnouncement' : ActorMethod<[bigint], boolean>,
  'adminGetAllTools' : ActorMethod<[], Array<Tool>>,
  'adminGetUsageStats' : ActorMethod<[], ToolSummary>,
  'adminGetVisitorStats' : ActorMethod<[], VisitorStats>,
  'adminListAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'adminLogin' : ActorMethod<[string, string], boolean>,
  'adminSetBetweenCardsAd' : ActorMethod<[boolean], undefined>,
  'adminSetHeaderAd' : ActorMethod<[boolean], undefined>,
  'adminSetSidebarAd' : ActorMethod<[boolean], undefined>,
  'adminSetToolEnabled' : ActorMethod<[ToolId, boolean], boolean>,
  'adminUpdateAnnouncement' : ActorMethod<[bigint, string, boolean], boolean>,
  'getActiveAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAdSettings' : ActorMethod<[], AdSettings>,
  'getEnabledTools' : ActorMethod<[], Array<Tool>>,
  'getUserGpaHistory' : ActorMethod<[string], Array<GpaCalculation>>,
  'loginStudent' : ActorMethod<
    [string, string],
    { 'ok' : [] | [StudentRecord], 'err' : [] | [string] }
  >,
  'recordToolUsage' : ActorMethod<[ToolId], undefined>,
  'registerStudent' : ActorMethod<
    [string, string],
    { 'ok' : [] | [StudentRecord], 'err' : [] | [string] }
  >,
  'saveGpaCalculation' : ActorMethod<
    [string, Array<GpaSubjectInput>, number, bigint],
    GpaCalculation
  >,
  'trackAuthenticatedVisitor' : ActorMethod<[], undefined>,
  'trackGuestVisitor' : ActorMethod<[GuestId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];