/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AnnouncementId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Announcement = IDL.Record({
  'id' : AnnouncementId,
  'active' : IDL.Bool,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
});
export const ToolId = IDL.Text;
export const Tool = IDL.Record({
  'id' : ToolId,
  'name' : IDL.Text,
  'usageCount' : IDL.Nat,
  'description' : IDL.Text,
  'enabled' : IDL.Bool,
});
export const ToolStats = IDL.Record({
  'usageCount' : IDL.Nat,
  'toolId' : ToolId,
});
export const ToolSummary = IDL.Record({
  'perTool' : IDL.Vec(ToolStats),
  'toolId' : ToolId,
  'totalUsage' : IDL.Nat,
});
export const VisitorStats = IDL.Record({ 'totalVisitors' : IDL.Nat });
export const AdSettings = IDL.Record({
  'betweenCardsAdEnabled' : IDL.Bool,
  'headerAdEnabled' : IDL.Bool,
  'sidebarAdEnabled' : IDL.Bool,
});
export const GpaSubject = IDL.Record({
  'marks' : IDL.Nat,
  'credits' : IDL.Nat,
  'subjectName' : IDL.Text,
  'gradePoints' : IDL.Float64,
  'letterGrade' : IDL.Text,
});
export const StudentId = IDL.Text;
export const GpaCalculation = IDL.Record({
  'id' : IDL.Nat,
  'subjects' : IDL.Vec(GpaSubject),
  'userId' : StudentId,
  'timestamp' : Timestamp,
  'calculatedGpa' : IDL.Float64,
  'totalCredits' : IDL.Nat,
});
export const HashedPassword = IDL.Text;
export const StudentRecord = IDL.Record({
  'id' : StudentId,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'hashedPassword' : HashedPassword,
});
export const GpaSubjectInput = IDL.Record({
  'marks' : IDL.Nat,
  'credits' : IDL.Nat,
  'subjectName' : IDL.Text,
});
export const GuestId = IDL.Text;

export const idlService = IDL.Service({
  'adminChangePassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'adminCreateAnnouncement' : IDL.Func([IDL.Text], [Announcement], []),
  'adminDeleteAnnouncement' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'adminGetAllTools' : IDL.Func([], [IDL.Vec(Tool)], []),
  'adminGetUsageStats' : IDL.Func([], [ToolSummary], []),
  'adminGetVisitorStats' : IDL.Func([], [VisitorStats], []),
  'adminListAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'adminSetBetweenCardsAd' : IDL.Func([IDL.Bool], [], []),
  'adminSetHeaderAd' : IDL.Func([IDL.Bool], [], []),
  'adminSetSidebarAd' : IDL.Func([IDL.Bool], [], []),
  'adminSetToolEnabled' : IDL.Func([ToolId, IDL.Bool], [IDL.Bool], []),
  'adminUpdateAnnouncement' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'getActiveAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAdSettings' : IDL.Func([], [AdSettings], ['query']),
  'getEnabledTools' : IDL.Func([], [IDL.Vec(Tool)], ['query']),
  'getUserGpaHistory' : IDL.Func([IDL.Text], [IDL.Vec(GpaCalculation)], []),
  'loginStudent' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Record({
          'ok' : IDL.Opt(StudentRecord),
          'err' : IDL.Opt(IDL.Text),
        }),
      ],
      [],
    ),
  'recordToolUsage' : IDL.Func([ToolId], [], []),
  'registerStudent' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Record({
          'ok' : IDL.Opt(StudentRecord),
          'err' : IDL.Opt(IDL.Text),
        }),
      ],
      [],
    ),
  'saveGpaCalculation' : IDL.Func(
      [IDL.Text, IDL.Vec(GpaSubjectInput), IDL.Float64, IDL.Nat],
      [GpaCalculation],
      [],
    ),
  'trackAuthenticatedVisitor' : IDL.Func([], [], []),
  'trackGuestVisitor' : IDL.Func([GuestId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AnnouncementId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Announcement = IDL.Record({
    'id' : AnnouncementId,
    'active' : IDL.Bool,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
  });
  const ToolId = IDL.Text;
  const Tool = IDL.Record({
    'id' : ToolId,
    'name' : IDL.Text,
    'usageCount' : IDL.Nat,
    'description' : IDL.Text,
    'enabled' : IDL.Bool,
  });
  const ToolStats = IDL.Record({ 'usageCount' : IDL.Nat, 'toolId' : ToolId });
  const ToolSummary = IDL.Record({
    'perTool' : IDL.Vec(ToolStats),
    'toolId' : ToolId,
    'totalUsage' : IDL.Nat,
  });
  const VisitorStats = IDL.Record({ 'totalVisitors' : IDL.Nat });
  const AdSettings = IDL.Record({
    'betweenCardsAdEnabled' : IDL.Bool,
    'headerAdEnabled' : IDL.Bool,
    'sidebarAdEnabled' : IDL.Bool,
  });
  const GpaSubject = IDL.Record({
    'marks' : IDL.Nat,
    'credits' : IDL.Nat,
    'subjectName' : IDL.Text,
    'gradePoints' : IDL.Float64,
    'letterGrade' : IDL.Text,
  });
  const StudentId = IDL.Text;
  const GpaCalculation = IDL.Record({
    'id' : IDL.Nat,
    'subjects' : IDL.Vec(GpaSubject),
    'userId' : StudentId,
    'timestamp' : Timestamp,
    'calculatedGpa' : IDL.Float64,
    'totalCredits' : IDL.Nat,
  });
  const HashedPassword = IDL.Text;
  const StudentRecord = IDL.Record({
    'id' : StudentId,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'hashedPassword' : HashedPassword,
  });
  const GpaSubjectInput = IDL.Record({
    'marks' : IDL.Nat,
    'credits' : IDL.Nat,
    'subjectName' : IDL.Text,
  });
  const GuestId = IDL.Text;
  
  return IDL.Service({
    'adminChangePassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'adminCreateAnnouncement' : IDL.Func([IDL.Text], [Announcement], []),
    'adminDeleteAnnouncement' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'adminGetAllTools' : IDL.Func([], [IDL.Vec(Tool)], []),
    'adminGetUsageStats' : IDL.Func([], [ToolSummary], []),
    'adminGetVisitorStats' : IDL.Func([], [VisitorStats], []),
    'adminListAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'adminSetBetweenCardsAd' : IDL.Func([IDL.Bool], [], []),
    'adminSetHeaderAd' : IDL.Func([IDL.Bool], [], []),
    'adminSetSidebarAd' : IDL.Func([IDL.Bool], [], []),
    'adminSetToolEnabled' : IDL.Func([ToolId, IDL.Bool], [IDL.Bool], []),
    'adminUpdateAnnouncement' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'getActiveAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAdSettings' : IDL.Func([], [AdSettings], ['query']),
    'getEnabledTools' : IDL.Func([], [IDL.Vec(Tool)], ['query']),
    'getUserGpaHistory' : IDL.Func([IDL.Text], [IDL.Vec(GpaCalculation)], []),
    'loginStudent' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Record({
            'ok' : IDL.Opt(StudentRecord),
            'err' : IDL.Opt(IDL.Text),
          }),
        ],
        [],
      ),
    'recordToolUsage' : IDL.Func([ToolId], [], []),
    'registerStudent' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Record({
            'ok' : IDL.Opt(StudentRecord),
            'err' : IDL.Opt(IDL.Text),
          }),
        ],
        [],
      ),
    'saveGpaCalculation' : IDL.Func(
        [IDL.Text, IDL.Vec(GpaSubjectInput), IDL.Float64, IDL.Nat],
        [GpaCalculation],
        [],
      ),
    'trackAuthenticatedVisitor' : IDL.Func([], [], []),
    'trackGuestVisitor' : IDL.Func([GuestId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };