/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface AdSettings {
    betweenCardsAdEnabled: boolean;
    headerAdEnabled: boolean;
    sidebarAdEnabled: boolean;
}
export interface Announcement {
    id: AnnouncementId;
    active: boolean;
    createdAt: Timestamp;
    text: string;
}
export type ToolId = string;
export type GuestId = string;
export interface VisitorStats {
    totalVisitors: bigint;
}
export interface ToolStats {
    usageCount: bigint;
    toolId: ToolId;
}
export interface Tool {
    id: ToolId;
    name: string;
    usageCount: bigint;
    description: string;
    enabled: boolean;
}
export interface ToolSummary {
    perTool: Array<ToolStats>;
    toolId: ToolId;
    totalUsage: bigint;
}
export type AnnouncementId = bigint;
export interface backendInterface {
    adminChangePassword(currentPassword: string, newPassword: string): Promise<boolean>;
    adminCreateAnnouncement(text: string): Promise<Announcement>;
    adminDeleteAnnouncement(id: bigint): Promise<boolean>;
    adminGetAllTools(): Promise<Array<Tool>>;
    adminGetUsageStats(): Promise<ToolSummary>;
    adminGetVisitorStats(): Promise<VisitorStats>;
    adminListAnnouncements(): Promise<Array<Announcement>>;
    adminLogin(email: string, password: string): Promise<boolean>;
    adminSetBetweenCardsAd(enabled: boolean): Promise<void>;
    adminSetHeaderAd(enabled: boolean): Promise<void>;
    adminSetSidebarAd(enabled: boolean): Promise<void>;
    adminSetToolEnabled(toolId: ToolId, enabled: boolean): Promise<boolean>;
    adminUpdateAnnouncement(id: bigint, text: string, active: boolean): Promise<boolean>;
    getActiveAnnouncements(): Promise<Array<Announcement>>;
    getAdSettings(): Promise<AdSettings>;
    getEnabledTools(): Promise<Array<Tool>>;
    recordToolUsage(toolId: ToolId): Promise<void>;
    trackAuthenticatedVisitor(): Promise<void>;
    trackGuestVisitor(guestId: GuestId): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminChangePassword(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminChangePassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminChangePassword(arg0, arg1);
            return result;
        }
    }
    async adminCreateAnnouncement(arg0: string): Promise<Announcement> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateAnnouncement(arg0);
            return result;
        }
    }
    async adminDeleteAnnouncement(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteAnnouncement(arg0);
            return result;
        }
    }
    async adminGetAllTools(): Promise<Array<Tool>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllTools();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllTools();
            return result;
        }
    }
    async adminGetUsageStats(): Promise<ToolSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetUsageStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetUsageStats();
            return result;
        }
    }
    async adminGetVisitorStats(): Promise<VisitorStats> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetVisitorStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetVisitorStats();
            return result;
        }
    }
    async adminListAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListAnnouncements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListAnnouncements();
            return result;
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return result;
        }
    }
    async adminSetBetweenCardsAd(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetBetweenCardsAd(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetBetweenCardsAd(arg0);
            return result;
        }
    }
    async adminSetHeaderAd(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetHeaderAd(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetHeaderAd(arg0);
            return result;
        }
    }
    async adminSetSidebarAd(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetSidebarAd(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetSidebarAd(arg0);
            return result;
        }
    }
    async adminSetToolEnabled(arg0: ToolId, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetToolEnabled(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetToolEnabled(arg0, arg1);
            return result;
        }
    }
    async adminUpdateAnnouncement(arg0: bigint, arg1: string, arg2: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateAnnouncement(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateAnnouncement(arg0, arg1, arg2);
            return result;
        }
    }
    async getActiveAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveAnnouncements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveAnnouncements();
            return result;
        }
    }
    async getAdSettings(): Promise<AdSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdSettings();
            return result;
        }
    }
    async getEnabledTools(): Promise<Array<Tool>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnabledTools();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnabledTools();
            return result;
        }
    }
    async recordToolUsage(arg0: ToolId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordToolUsage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordToolUsage(arg0);
            return result;
        }
    }
    async trackAuthenticatedVisitor(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.trackAuthenticatedVisitor();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackAuthenticatedVisitor();
            return result;
        }
    }
    async trackGuestVisitor(arg0: GuestId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.trackGuestVisitor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackGuestVisitor(arg0);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
